### ISSUE TITLE
Composer installing PMAStandard in wrong directory

### ISSUE THREAD

**Issue by arimourao** [phpmyadmin/coding-standard#1]
I followed the instructions here, inside the folder "coding-standard" was PMAStandard folder and another composer.json. I ran composer install inside folder and another vendor folder was created inside "coding-standard". I was still getting errors, so I moved the PMAStandard from:
`vendor/phpmyadmin/coding-standard`
to
`vendor/phpmyadmin/coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards`

and then I got it working. Must be something wrong with the installation paths.

**Comment by nijel** [comment]
Why did you run composer from the subfolder, that should not be necessary. Just install it in a project where you want to use it and install into phpcs:

```
composer require --dev phpmyadmin/coding-standard
phpcs --config-set installed_paths ./vendor/phpmyadmin/coding-standard
```
