### ISSUE TITLE
Upgrade PHP_CodeSniffer to v3

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/coding-standard#3]
Upgrade [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) to version `^3.0`.

[Version 3.0 Upgrade Guide](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide)

**Comment by nijel** [comment]
Good idea, the upgrade has to change composer.json in phpmyadmin repository as well.
